const SectionTitles = {
  name: "titles",
  label: "Section Titles",
  path: "src/content/sectionTitles",
  fields: [
    {
      name: "hero",
      label: "Hero Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "highlightedText",
          label: "Highlighted Text",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
        {
          name: "lightImg",
          label: "Light Image",
          type: "image",
          required: true,
        },
        {
          name: "darkImg",
          label: "Dark Image",
          type: "image",
          required: true,
        },
      ],
    },
    {
      name: "features",
      label: "Features Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "about",
      label: "About Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "highlightedText",
          label: "Highlighted Text",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
        {
          name: "lightImg",
          label: "Light Image",
          type: "image",
          required: true,
        },
        {
          name: "darkImg",
          label: "Dark Image",
          type: "image",
          required: true,
        },
      ],
    },
    {
      name: "featureTab",
      label: "Feature Tab Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
        {
          name: "lightImg",
          label: "Light Image",
          type: "image",
          required: true,
        },
        {
          name: "darkImg",
          label: "Dark Image",
          type: "image",
          required: true,
        },
      ],
    },
    {
      name: "funFact",
      label: "Fun Fact Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
        {
          name: "img",
          label: "Image",
          type: "image",
          required: true,
        },
      ],
    },
    {
      name: "integrations",
      label: "Integrations Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "cta",
      label: "CTA Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "img",
          label: "Image",
          type: "image",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "faq",
      label: "FAQ Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "highlightedText",
          label: "Highlighted Text",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "testimonial",
      label: "Testimonial Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "pricing",
      label: "Pricing Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
    {
      name: "blogs",
      label: "Blogs Section",
      type: "object",
      required: true,
      fields: [
        {
          name: "title",
          label: "Title",
          type: "string",
          required: true,
        },
        {
          name: "tag",
          label: "Tag",
          type: "string",
          required: true,
        },
        {
          name: "desc",
          label: "Description",
          component: "textarea",
          type: "string",
          required: true,
        },
      ],
    },
  ],
};

export default SectionTitles;
